name: Build Docker image
description: Build a Docker image and optionally upload it as artifact

inputs:
  context:
    description: The build's context
    required: false
    default: .
  file:
    description: Path to the Dockerfile to build
    required: false
    default: Dockerfile
  build-args:
    description: The arguments to build the image with
    required: false
  target:
    description: The target stage to build
    required: false
  name:
    description: The name to call the image
    required: true
  upload:
    description: Whether to upload the image as artifact
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0

    - name: Build image
      uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8 # tag=v3.0.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        build-args: |
          ${{ inputs.build-args }}
        cache-from: type=gha,scope=${{ format('{0}/{1}', inputs.context, inputs.file) }}
        cache-to: type=gha,scope=${{ format('{0}/{1}', inputs.context, inputs.file) }}
        tags: |
          ${{ inputs.name }}
        target: ${{ inputs.target }}
        outputs: type=docker,dest=/tmp/${{ inputs.name }}.tar

    - name: Upload artifact
      if: fromJSON(inputs.upload)
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
      with:
        name: ${{ inputs.name }}
        path: /tmp/${{ inputs.name }}.tar
