name: Build Docker image
description: Build a Docker image and optionally upload it as artifact

inputs:
  context:
    description: The build's context
    required: false
    default: .
  file:
    description: Path to the Dockerfile to build
    required: false
    default: Dockerfile
  build-args:
    description: The arguments to build the image with
    required: false
  target:
    description: The target stage to build
    required: false
  name:
    description: The name to call the image
    required: true
  upload:
    description: Whether to upload the image as artifact
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Build image
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        build-args: |
          ${{ inputs.build-args }}
        cache-from: type=gha,scope=${{ github.ref_name }}-${{ inputs.file }}-${{ inputs.target || 'main' }}
        cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ inputs.file }}-${{ inputs.target || 'main' }}
        tags: |
          ${{ inputs.name }}
        target: ${{ inputs.target }}
        outputs: type=docker,dest=/tmp/${{ inputs.name }}.tar

    - name: Upload artifact
      if: fromJSON(inputs.upload)
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: ${{ inputs.name }}
        path: /tmp/${{ inputs.name }}.tar
