name: Build Docker image
description: Build a Docker image and optionally upload it as artifact

inputs:
  file:
    description: Path to the Dockerfile to build
    required: true
  build-args:
    description: The arguments to build the image with
    required: false
  name:
    description: The name to call the image
    required: true
  upload:
    description: Whether to upload the image as artifact
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.file }}
        build-args: |
          ${{ inputs.build-args }}
        cache-from: type=gha,scope=${{ inputs.file }}
        cache-to: type=gha,scope=${{ inputs.file }}
        tags: |
          ${{ inputs.name }}
        outputs: type=docker,dest=/tmp/${{ inputs.name }}.tar

    - name: Upload artifact
      if: fromJSON(inputs.upload)
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.name }}
        path: /tmp/${{ inputs.name }}.tar
