name: Build Docker image
description: Build a Docker image and optionally upload it as artifact

inputs:
  file:
    description: Path to the Dockerfile to build
    required: false
  build-args:
    description: The arguments to build the image with
    required: false
  target:
    description: The target stage to build
    required: false
  name:
    description: The name to call the image
    required: true
  upload:
    description: Whether to upload the image as artifact
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # tag=v1

    - name: Build image
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # tag=v2
      with:
        context: .
        file: ${{ inputs.file }}
        build-args: |
          ${{ inputs.build-args }}
        cache-from: type=gha,scope=${{ inputs.file || 'Dockerfile' }}
        cache-to: type=gha,scope=${{ inputs.file || 'Dockerfile' }}
        tags: |
          ${{ inputs.name }}
        target: ${{ inputs.target }}
        outputs: type=docker,dest=/tmp/${{ inputs.name }}.tar

    - name: Upload artifact
      if: fromJSON(inputs.upload)
      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # tag=v2
      with:
        name: ${{ inputs.name }}
        path: /tmp/${{ inputs.name }}.tar
