name: Load Docker image
description: Load a Docker image and optionally download it first from the workflow artifacts

inputs:
  name:
    description: The name of the image
    required: true
  download:
    description: Whether to download the image from the workflow artifacts
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Download artifact
      if: fromJSON(inputs.download)
      uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
      with:
        name: ${{ inputs.name }}
        path: /tmp

    - name: Load image
      shell: bash
      run: |
        docker load --input /tmp/${{ inputs.name }}.tar

