name: Load Docker image
description: Load a Docker image and optionally download it first from the workflow artifacts

inputs:
  name:
    description: The name of the image
    required: true
  download:
    description: Whether to download the image from the workflow artifacts
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0

    - name: Download artifact
      if: fromJSON(inputs.download)
      uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
      with:
        name: ${{ inputs.name }}
        path: /tmp

    - name: Load image
      shell: bash
      run: |
        docker load --input /tmp/${{ inputs.name }}.tar

