name: Load Docker image
description: Load a Docker image and optionally download it first from the workflow artifacts

inputs:
  name:
    description: The name of the image
    required: true
  download:
    description: Whether to download the image from the workflow artifacts
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3.2.0

    - name: Download artifact
      if: fromJSON(inputs.download)
      uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
      with:
        name: ${{ inputs.name }}
        path: /tmp

    - name: Load image
      shell: bash
      run: |
        docker load --input /tmp/${{ inputs.name }}.tar

