name: Load Docker image
description: Load a Docker image and optionally download it first from the workflow artifacts

inputs:
  name:
    description: The name of the image
    required: true
  download:
    description: Whether to download the image from the workflow artifacts
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # tag=v1

    - name: Download artifact
      if: fromJSON(inputs.download)
      uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
      with:
        name: ${{ inputs.name }}
        path: /tmp

    - name: Load image
      shell: bash
      run: |
        docker load --input /tmp/${{ inputs.name }}.tar

